### ISSUE TITLE
Can't connect to remote server

### ISSUE THREAD

**Issue by crusher72** [CoiniumServ/CoiniumServ#750]
Here is the log file:

08/28/2016 23:01:40 -07:00 [Information] [ConfigManager] [global] CoiniumServ Aurora 0.2.4.39283 warming-up..
08/28/2016 23:01:40 -07:00 [Information] [PlatformManager] [global] Running over .Net, framework: 4.5 (v4.0.30319.42000).
08/28/2016 23:01:41 -07:00 [Error] [StorageConfig] [global] Storage will be not working as no valid storage configuration was found!
08/28/2016 23:01:41 -07:00 [Information] [ConfigManager] [global] Discovered a total of 1 enabled pool configurations: [Litecoin]
08/28/2016 23:01:41 -07:00 [Debug] [Pool] [Litecoin] Generated cryptographically random instance Id: 1744485206
08/28/2016 23:01:41 -07:00 [Debug] [n/a] [global] Metrics: GlobalContext Name set to CoiniumServ
08/28/2016 23:01:41 -07:00 [Information] [BanManager] [Litecoin] No expired bans found to be cleared [remaining bans: 0].
08/28/2016 23:01:41 -07:00 [Information] [JobManager] [Litecoin] Broadcasted new job 0x1 to 0 subscribers as no new blocks found for last 55 seconds
08/28/2016 23:01:41 -07:00 [Information] [NetworkInfo] [Litecoin] symbol: LTC algorithm: scrypt version: 100400 protocol: 70003 wallet: 60000 network difficulty: 53594.49143342 block difficulty: 3512368590.58 network hashrate: 1.51 TH/s network: mainnet peers: 8 blocks: 1052770 errors: none 
08/28/2016 23:01:41 -07:00 [Information] [StratumServer] [Litecoin] Stratum server listening on 0.0.0.0:7272
08/28/2016 23:01:41 -07:00 [Error] [PoolManager] [global] Error recaching statistics; The method or operation is not implemented.
08/28/2016 23:01:41 -07:00 [Debug] [StatisticsManager] [global] Recached statistics - took 0.033 seconds
08/28/2016 23:02:02 -07:00 [Error] [ExchangeApi] [global] Unable to connect to the remote server
08/28/2016 23:02:02 -07:00 [Error] [CryptsyClient] [global] Cannot perform runtime binding on a null reference
08/28/2016 23:02:02 -07:00 [Debug] [MarketManager] [global] Recached market data - took 21.385 seconds

I can't get it to connect to the remote server. I do not have database enabled.

Many and much thanks to all who help!

**Comment by bonesoul** [comment]
disable cryptsy

**Comment by crusher72** [comment]
Thanks for the reply. How do I go about disabling cryptsy? I looked in the configs, but did not see anything.

**Comment by crusher72** [comment]
I  think I figured it out. I would have to recompile modifying cryptsy?

**Comment by BaalMcKloud** [comment]
check CoiniumServ\src\CoiniumServ\Markets\MarketManager.cs on line 56 !
remove " ICryptsyClient cryptsyClient " and build again.

**Comment by crusher72** [comment]
Thank you so much! Appreciate this!
