### ISSUE TITLE
External connections fail, Private Network IP working

### ISSUE THREAD

**Issue by crusher72** [CoiniumServ/CoiniumServ#751]
I can't get webserver to listen on local network ip for incoming connections. I understand you need to enter your web address in the config file. But then what? Bind it to 127.0.0.1? Or what is the next thing you need to do to listen properly? I thought of Xampp, but is that necessary?

Also the hashrate is showing zero even when mining on my localhost 127.0.0.1 or private ip 192.168.0.2 with plenty of accepted shares.

Please help. Many thanks!
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/37401734-can-t-get-webserver-to-listen-on-local-ip?utm_campaign=plugin&utm_content=tracker%2F401667&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F401667&utm_medium=issues&utm_source=github).
</bountysource-plugin>

**Comment by crusher72** [comment]
Update**

I have it listening locally  fine, but outside connections fail, even with port forwarding correct, and firewall off. Windows 7.

Why are the outside connections failing?

**Comment by psofe** [comment]
Try binding to 0.0.0.0 ?

**Comment by crusher72** [comment]
Thank you for the reply. I just tried that and no dice. I just tried bind "" and it got both localhost and my local network ip to connect fine. If I enter 0.0.0.0 my local network ip of 192.168.0.2 fails to connect. That is the Ip I have listening to the external public ip.

Hmm, still trying...

**Comment by psofe** [comment]
I think you can use IP ranges/masks, ie: 192.168.0.0/24

**Comment by crusher72** [comment]
Wow awesome, thanks for that! I wonder why it would fail from the outside public ip but not the local network one though?

I will try the IP ranges

**Comment by crusher72** [comment]
I have it setup on 127.0.0.1 restarted computer. I have connections working on localhost or 127.0.0.1 and 192.168.0.2 but it still says unable to connect from outside public ip. Coinpoolz.com is the webaddress forwarding to my public ip. What is wrong here?

**Comment by crusher72** [comment]
I got it to work!

The issue was Arris routers are strange beasts. I turned ON the router's firewall and it worked! Crazy eh?
